baseURL: "https://iamb4uc.xyz" 
languageCode: en-us
title: B4UC
theme: PaperMod


params:
  homeInfoParams:
    Title: "Hello!!"
    Content: Welcome this project site. This website is created to test out some of my programming skills and my writting skills since I would be writting about tech and other stuff here. To know more about me visit the about section of this page. Hope I solved/helped your problems.

  socialIcons:
    - name: github
      url: "https://github.com/iamb4uc"
    - name: mastodon
      url: "https://mastodon.social/@b4uc"
    - name: telegram
      url: "https://t.me/susssywusssy"


  cover:
    linkFullImages: false 
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true


menu:
  main:
    - identifier: about
      name: About Me
      url: /about
      weight: 10
    - identifier: posts 
      name: Posts 
      url: /posts/
      weight: 20
    - identifier: archives 
      name: Archives
      url: /archives
      weight: 30
