baseURL: "https://iamb4uc.xyz" 
languageCode: en-us
title: B4UC
theme: PaperMod


params:
  profileMode:
    enabled: true
    imageUrl: "img/profile.jpeg"
    subtitle: Welcome!! this is a repository of my personal projects, works, CV, and other stuffs like blogs and tutorials. To know more about me visit [**About**](/about). 
      To find blogs based to topics visit [**Tags**](/tags)
      or visit [**Projects**](/projects) and [**CV**](/cv) to know more about works and achivements.
    buttons:
      - name: Archives
        url: "/archives/"
      - name: Topics
        url: "/tags/"



  socialIcons:
    - name: github
      url: "https://github.com/iamb4uc"
    - name: mastodon
      url: "https://mastodon.social/@b4uc"
    - name: telegram
      url: "https://t.me/susssywusssy"
    - name: dev 
      url: "https://dev.to/iamb4uc"
    - name: email
      url: "mailto:b4uc@tuta.io"


  cover:
    linkFullImages: false 
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true


menu:
  main:
    - identifier: posts 
      name: Posts 
      url: /posts/
      weight: 10
    - identifier: projects 
      name: Projects 
      url: /projects/
      weight: 20
    - identifier: tags 
      name: Tags 
      url: /tags/
      weight: 30
    - identifier: archives 
      name: Archives
      url: /archives
      weight: 40
    - identifier: about
      name: About
      url: /about
      weight: 50
