baseURL: "https://iamb4uc.xyz" 
languageCode: en-us
title: B4UC
theme: PaperMod


params:
  homeInfoParams:
    Title: "Hello!!"
    Content: Welcome to this website.  


  socialIcons:
    - name: github
      url: "https://github.com/iamb4uc"
    - name: mastodon
      url: "https://mastodon.social/@b4uc"
    - name: telegram
      url: "https://t.me/susssywusssy"
    - name: medium 
      url: "https://medium.com/@b4uc"
    - name: dev 
      url: "https://dev.to/iamb4uc"


  cover:
    linkFullImages: false 
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true


menu:
  main:
    - identifier: posts 
      name: Posts 
      url: /posts/
      weight: 10
    - identifier: archives 
      name: Archives
      url: /archives
      weight: 20
    - identifier: about
      name: About
      url: /about
      weight: 30
